export enum UserTypes {
    USER_SEARCH = "USER_SEARCH/GET",
    USER_SEARCH_SUCCESS = "USER_SEARCH/SUCCESS",
    USER_SEARCH_ERROR = "USER_SEARCH/ERROR",
    USER_DETAILS = "USER_DETAILS/SUCCESS",
    USER_DETAILS_SUCCESS = "USER_DETAILS/SUCCESS",
    USER_DETAILS_ERROR = "USER_DETAILS/ERROR",
    USER_REPOSITORIES ="USER_REPOSITORIES/GET",
    USER_REPOSITORIES_SUCCESS ="USER_REPOSITORIES/SUCCESS",
    USER_REPOSITORIES_ERROR ="USER_REPOSITORIES/ERROR",
    SEARCH_KEY = "SEARCH_KEY/SET",
    PAGE_NUMBER = "PAGE_NUMBER"
}